### PR TITLE
Include user in access logs

### PR DESCRIPTION
**Pull request by essen**
This is the management side of the fix for: https://github.com/rabbitmq/rabbitmq-management/issues/760

As a bonus it will also work for the Web plugins when HTTP authentication is used.

### CODE REVIEW

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Awesome, we just need to make sure we don't forget to rename `uaa_client_id` when we do it in the OAuth 2 plugin 😄

**Comment by michaelklishin** [comment]
Backported to `v3.8.x` but decided to leave it out of `v3.7.x` because it includes OAuth 2-specific bits. That's fine, `v3.7.x` support will only last for a few more months.

**Comment by lukebakken** [comment]
Will this change address the "login" part of this request? [`rabbitmq-users` discussion](https://groups.google.com/d/topic/rabbitmq-users/99nJA-WgiTM/discussion)

**Comment by essen** [comment]
If management is configured to write access logs then the access logs will include the user for all relevant requests, but there is no log indicating the user just logged in (because the credentials are sent with every request so it's like you log in every time).

**Pull request merged**
